import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.scss'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import { useForm } from 'react-hook-form'

const inter = Inter({ subsets: ['latin'] })

type FormValues = {
  firstName: string
  lastName: string
}

export default function Home() {
  const {register, handleSubmit, formState, watch, getValues, reset, formState: {errors, isSubmitSuccessful} } = useForm<FormValues>({
    defaultValues: {
      firstName: 'Sabrina',
      lastName: 'Mayzura',
    }
  });

  console.log("error ni bang", errors)

  React.useEffect(() => {
    if(formState.isSubmitSuccessful){
      reset({
        firstName: "Timothee",
        lastName: "Chalamet"
      })
    }
  }, [formState, reset])

  return (
    <>
      <Head>
        <title>Van Gogh Library</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <section className='bg-yellow-100 pt-20'>
        <Navbar/>
        <main className='bg-yellow-100'>
            <section className='min-h-screen flex items-center justify-center'>
                <form onSubmit={handleSubmit((data)=>{
                    console.log(data)
                })}
                className='flex flex-col gap-3' action="">
                  <p className='text-black font-semibold' >Register For Campaign</p>
                    <input {...register("firstName", {required: 'Ini required', minLength:{value: 4, message:'Minimal 4'}})} type="text" placeholder='First Name'/>
                    <p>{errors.firstName?.message}</p>
                    <input {...register("lastName")} type="text" placeholder='Last Name'/>
                    <input type="submit" className='text-black bg-yellow-500 p-1 rounded-md'  />
                    <button type='button' className='bg-green-500 text-white p-1 rounded-md' onClick={()=>{
                      reset(
                        {
                          ...getValues(),
                          firstName: 'Pedro',
                          lastName: 'Pascal'
                        }
                      )
                    }}>
                      Reset
                    </button>
                </form>
            </section>
        </main>
        <Footer/>
      </section>
    </>
  )
}
